### Get Products

GET http://localhost:3000/api/products

### With parameters

GET http://localhost:3000/api/products?label=t-shirt&colors=red&sizes=XL&minPrice=100&maxPrice=200

### Get product by id

GET http://localhost:3000/api/product/1

### Update product

PUT http://localhost:3000/api/product/1
Content-Type: application/json

{
    "price": 150
}

### Create product

POST http://localhost:3000/api/product
Content-Type: application/json

{
    "label": "t-shirt",
    "price": 100,
    "colors": ["red", "blue"],
    "sizes": ["S", "M", "L", "XL"],
    "description": "This is a t-shirt"
}

### Delete product
DELETE http://localhost:3000/api/product/4

### Login
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "username": "admin",
    "password": "password123"
}

### Get cart
GET http://localhost:3000/api/cart

### Add to cart
POST http://localhost:3000/api/cart
Content-Type: application/json

{
    "product_id": 43,
    "size": "S",
    "color": "red"
}

### Get reviews
GET http://localhost:3000/api/review/43

### Place review
POST http://localhost:3000/api/review/43
Content-Type: application/json

{
    "rating": 5,
    "text": "This is a great product"
}

### Delete from cart
DELETE http://localhost:3000/api/cart/43


### Create order
POST http://localhost:3000/api/order
Content-Type: application/json

{
    "provider": "paypal",
    "cardnumber": "1234567890123456",
    "expiration": "12/2020",
    "cvc": "123",
    "firstname": "John",
    "lastname": "Doe",
    "email": "johndoe@gmail.com",
    "address": "1234 Main St",
    "city": "New York",
    "country": "USA",
    "zip": "10001",
    "phonenumber": "1234567890"
}